// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ebgzgjoxcgfhafwgfqix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZ3pnam94Y2dmaGFmd2dmcWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MTc2MzcsImV4cCI6MjA4ODk5MzYzN30.35Ve7gQOLhrWF_0h_BHrxZfiPhutOC08iITLzKMnGrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);