// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://blrqybhzpcasfcgbhkqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJscnF5Ymh6cGNhc2ZjZ2Joa3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNDEwNTksImV4cCI6MjA3ODgxNzA1OX0.HtFyhbVZXTUwSmVIfrST1JGHjnFO1PHNTCc_Y701WgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);